#Whenever someone changes the python code, 
#The linter will check if the syntax, format, and indentation (linting) are correct or not
name: Auto linter

on:
  push:
    paths: "*.py"

jobs:
  Code:
    runs-on: ubuntu-latest
    steps:
#This step will automatically clone the code of the current branch
      - name: Checkout the code
        uses: actions/checkout@v7
# 2. Install and configure Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Exact version or version range 
#This step will install the linting tool
      - name: Install Python linter
        run: pip install ruff
#This step will run the linter
      - name: Check the files for linting
        run: ruff check .
